
services:
  todo_frontend:
    build:
      context: ./todo_frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Frontend will be accessible on port 3000
    depends_on:
      - todo_backend  

  todo_backend:
    build:
      context: ./todo_backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"  # Backend will be accessible on port 4000
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase  # MongoDB connection string
    depends_on:
      - mongo  

  mongo:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db  # Data persistence for MongoDB
    ports:
      - "27017:27017"  # MongoDB will be accessible on port 27017

volumes:
  mongodb_data:  # Volume to persist MongoDB data
